# Generated by Django 2.2.6 on 2019-10-02 11:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buchung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField(default=django.utils.timezone.now)),
                ('nummer', models.IntegerField(blank=True, null=True)),
                ('bemerkung', models.CharField(blank=True, max_length=100, null=True)),
                ('buchungstext', models.CharField(blank=True, max_length=100, null=True)),
                ('beschreibung', models.CharField(default='', max_length=100)),
                ('is_multibuchung', models.BooleanField(default=False)),
                ('betrag', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DeviseWertpapier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('anzeigesymbol', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=50, unique=True)),
                ('stueckelung', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Devisen/Wertpapiere',
            },
        ),
        migrations.CreateModel(
            name='DeviseWertpapierTyp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Devisen/Wertpapiertypen',
            },
        ),
        migrations.CreateModel(
            name='KontoTyp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Kontotypen',
            },
        ),
        migrations.CreateModel(
            name='MultiBuchung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multibuchung_id', models.IntegerField()),
                ('buchung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haushalt.Buchung')),
            ],
        ),
        migrations.CreateModel(
            name='Konto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('kontonummer', models.IntegerField(null=True)),
                ('beschreibung', models.CharField(max_length=100, null=True)),
                ('bemerkung', models.CharField(max_length=100, null=True)),
                ('versteckt', models.BooleanField(default=False)),
                ('steuerrelevant', models.BooleanField(default=False)),
                ('platzhalter', models.BooleanField(default=False)),
                ('devise_wertpapier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haushalt.DeviseWertpapier')),
                ('elternkonto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eltern_konto', to='haushalt.Konto')),
                ('kontotyp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haushalt.KontoTyp')),
            ],
            options={
                'verbose_name_plural': 'Konten',
            },
        ),
        migrations.AddField(
            model_name='devisewertpapier',
            name='wertpapiertyp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haushalt.DeviseWertpapierTyp'),
        ),
        migrations.AddField(
            model_name='buchung',
            name='konto1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abbuchung', to='haushalt.Konto'),
        ),
        migrations.AddField(
            model_name='buchung',
            name='konto2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zubuchung', to='haushalt.Konto'),
        ),
    ]
