# Generated by Django 2.2.6 on 2019-11-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haushalt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='konto',
            name='ebene',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
