# Generated by Django 2.2.6 on 2019-10-09 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('haushalt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='konto',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='konten', to=settings.AUTH_USER_MODEL),
        ),
    ]
