# Generated by Django 2.2.6 on 2019-12-09 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('haushalt', '0002_konto_ebene'),
    ]

    operations = [
        migrations.AddField(
            model_name='devisewertpapier',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='devisen_wertpapiere', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='devisewertpapier',
            constraint=models.UniqueConstraint(fields=('name', 'owner'), name='devise_wertpapier_owner'),
        ),
    ]
